[workspace.package]
version = "0.5.3"
authors = ["linggen77@gmail.com"]
edition = "2021"

[workspace]
members = [
    "api",
    "architect",
    "context",
    "core",
    "embeddings",
    "enhancement",
    "ingestion",
    "intent",
    "llm",
    "storage",
    "mcp-server",
]
resolver = "2"
